import pandas as pd
exf=pd.ExcelFile("animax.xlsx")
df1=exf.parse('S1')
df2=exf.parse('S2')
df3=exf.parse('S3')
df4=exf.parse('S4')
df5=exf.parse('S5')
df6=exf.parse('S6')
df7=exf.parse('S7')
df8=exf.parse('S8')
df9=exf.parse('S9')
df10=exf.parse('S10')

print(df1)

df1.to_csv('S1_convert.csv')
df2.to_csv('S2_convert.csv')
df3.to_csv('S3_convert.csv')
df4.to_csv('S4_convert.csv')
df5.to_csv('S5_convert.csv')
df6.to_csv('S6_convert.csv')
df7.to_csv('S7_convert.csv')
df8.to_csv('S8_convert.csv')
df9.to_csv('S9_convert.csv')
df10.to_csv('S10_convert.csv')
